AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Max: 35

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
