language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
gemfile:
  - gemfiles/rails_4.2.8.gemfile
  - gemfiles/rails_5.0.3.gemfile
  - gemfiles/rails_5.1.1.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
